### ISSUE TITLE
False positive "udisks2 & udisks 2014-03-10 2.1.3 / 1.0.5"

### ISSUE THREAD

**Issue by R-a-l-f** [ilpianista/arch-audit#11]
Hi,

0.1.5 does show a false positive.

[rocketmouse@archlinux ~]$ grep arch-audit /var/log/pacman.log | tail -1
[2016-11-08 23:52] [ALPM] upgraded arch-audit (0.1.4-1 -> 0.1.5-1)
[rocketmouse@archlinux ~]$ echo $(arch-audit -f "%n | " | sort) | sed s/.$//
bzip2 | cinnamon-screensaver | jasper | lib32-gdk-pixbuf2 | libimobiledevice | libtiff | libusbmuxd | libwmf | udisks 
[rocketmouse@archlinux ~]$ arch-audit --upgradable --quiet
udisks>=2.1.3 / 1.0.5
[rocketmouse@archlinux ~]$ pacman -Si $(arch-audit --upgradable -f "%n") | grep -A3 "Repository      : "
Repository      : extra
Name            : udisks
Version         : 1.0.5-3
Description     : Disk Management Service
[rocketmouse@archlinux ~]$ sudo pacman -U /var/cache/aur/current/arch-audit-0.1.4-1-x86_64.pkg.tar.xz
[snip]
[rocketmouse@archlinux ~]$ grep arch-audit /var/log/pacman.log | tail -1
[2016-11-09 00:33] [ALPM] downgraded arch-audit (0.1.5-1 -> 0.1.4-1)
[rocketmouse@archlinux ~]$ echo $(arch-audit -f "%n | " | sort) | sed s/.$//
bzip2 | cinnamon-screensaver | jasper | lib32-gdk-pixbuf2 | libimobiledevice | libtiff | libusbmuxd | libwmf 
[rocketmouse@archlinux ~]$ arch-audit --upgradable --quiet
[rocketmouse@archlinux ~]$

Regards,
Ralf

**Comment by ilpianista** [comment]
Hi, I consider this an error in the CVE page. I just fixed it, please try again!

**Comment by ilpianista** [comment]
Hi,
I "fixed" this by editing the CVE page and by splitting udisks entries. (Previusly the same row was used for both udisks packages: udisks and udisks2).
That entry is 2 years old and shouldn't be the usual procedure.
