### ISSUE TITLE
Define exit code 1 when vulnerable packages are found

### ISSUE THREAD

**Issue by mboelen** [ilpianista/arch-audit#3]
Thanks for your work on this tool. I'm added support for it in [Lynis](https://github.com/CISOfy/lynis) to help promoting it to Arch Linux users.

The current issue with the tool is that exit code 0 is used, even when vulnerable packages are found. It would be great if there would be a --silent option, together with an exit code of 1. This way it would be easy for scripts and other tools to determine if there are any vulnerable packages.

**Comment by anthraxx** [comment]
@mboelen yay thats awesome :fireworks: (sry for hijacking the thread, was just exited :yum: )

**Comment by ilpianista** [comment]
indeed it's!!

but I'm wondering if the exit code 1 is the best option here. Couldn't lynis just check how many lines arch-audit printed?

**Comment by mboelen** [comment]
Sure, Lynis could do that. Yet for integrating a great tool, it would be better if it leverages exit codes, so other tools can rely on that. Because if the output (lines) change in the future, then it might trigger a false positive. While exit code higher than 0 could always keep its meaning.

In the meantime the first few bits in Lynis are implemented, testing right now to make sure it works properly.

**Comment by ilpianista** [comment]
I would keep exit code 1 for errors.
And I fear that using a different exit code to notify vulnerable packages will possibly break scripting (e.g. `arch-audit || echo "Failed!"`).

However `--quiet` will never display anything else but package names.

**Comment by mboelen** [comment]
Sure, I understand and also that you want to keep the number of options as low as possible, as that simplifies the help and usage of the tool. Yet an option to parse the output easily would be really great.

$ arch-audit --brief-output
packages=248
vulnerable=3
version=0.234

Would that be an idea?

**Comment by ilpianista** [comment]
Sure, I just read your blog post and I was going to propose that flag to you :-)
